name: Deploy to VPS

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup SSH key
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.VPS_SSH_KEY }}
        
    - name: Add VPS to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
        
    - name: Deploy to VPS
      run: |
        ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'ENDSSH'
          set -e
          echo "Starting deployment..."
          
          # Navigate to project directory
          cd ${{ secrets.VPS_PATH }}
          
          # Pull latest changes
          echo "Pulling latest changes from GitHub..."
          git pull origin main
          
          # Install/update dependencies
          echo "Installing dependencies..."
          cd multimodal-llm-platform/backend
          pip3 install -r requirements.txt
          
          # Restart services
          echo "Restarting services..."
          sudo systemctl restart autopicker-backend
          sudo systemctl restart nginx
          
          # Health check
          echo "Performing health check..."
          sleep 5
          curl -f http://localhost:8000/health || exit 1
          
          echo "Deployment completed successfully!"
        ENDSSH
        
    - name: Verify deployment
      run: |
        echo "Verifying deployment..."
        sleep 10
        curl -f http://${{ secrets.VPS_HOST }}:8000/health || exit 1
        echo "Deployment verification successful!"