use_default_settings: true

server:
  port: 8080
  bind_address: "0.0.0.0"
  secret_key: "change-this-secret-key-in-production"
  limiter: false
  public_instance: false

search:
  safe_search: 0
  autocomplete: ""
  default_lang: "en"
  formats:
    - html
    - json

engines:
  - name: google
    engine: google
    shortcut: g
    use_mobile_ui: false

  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    
  - name: bing
    engine: bing
    shortcut: bi

  - name: startpage
    engine: startpage
    shortcut: sp

  - name: wikipedia
    engine: wikipedia
    shortcut: wp
    base_url: 'https://{language}.wikipedia.org/'

  - name: wikidata
    engine: wikidata
    shortcut: wd
    timeout: 5.0
    weight: 2

enabled_plugins:
  - 'Hash plugin'
  - 'Search on category select'
  - 'Self Information'
  - 'Tracker URL remover'
  - 'Ahmia blacklist'

disabled_engines:
  - 'Brave'
  - 'Yandex'